import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useMemo } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { AvatarPresenter } from "./components/AvatarPresenter";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { Subtitle } from "./components/Subtitle";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { AVATAR_CONFIG } from "./registry/avatarConfig";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  // Auto 模式未启动时抑制 stepper 的 Space 监听：否则启动播放的同一次按键
  // 会被当成"前进一步"，第 0 步的画面和配音会被跳过。
  const stepper = useStepper(CHAPTERS, {
    suppressSpace: mode === "auto" && !autoStarted,
  });
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  const { getAudioEl } = useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  // avatar-mount:v1 —— 确定性接线契约：字幕与数字人由 registry 数据驱动。
  // VideoForge 的 avatar_wire 阶段只重写 registry/avatarConfig.ts，不改本文件。
  const avatarAudioSources = useMemo(
    () =>
      AVATAR_CONFIG.enabled
        ? CHAPTERS.flatMap((chapter) =>
            chapter.narrations.map(
              (_, index) =>
                `${import.meta.env.BASE_URL}audio/${chapter.id}/${index + 1}.mp3`,
            ),
          )
        : [],
    [],
  );

  useEffect(() => {
    if (!AVATAR_CONFIG.enabled) return;
    const rootStyle = document.documentElement.style;
    rootStyle.setProperty("--stage-pad-x-end", `${AVATAR_CONFIG.reservePx}px`);
    rootStyle.setProperty("--avatar-window-w", `${AVATAR_CONFIG.windowWidthPx}px`);
    rootStyle.setProperty("--avatar-window-h", `${AVATAR_CONFIG.windowHeightPx}px`);
  }, []);

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
        <Subtitle
          chapterId={ch.id}
          step={stepper.cursor.step}
          fallbackText={stepText}
          getAudioEl={getAudioEl}
        />
        {AVATAR_CONFIG.enabled && (
          <AvatarPresenter
            getAudioEl={getAudioEl}
            globalStep={stepper.globalIndex}
            audioSources={avatarAudioSources}
          />
        )}
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
