import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useMemo } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { AvatarPresenter } from "./components/AvatarPresenter";
import { CameraLayer } from "./components/CameraLayer";
import { EffectsProvider } from "./components/EffectsContext";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { Subtitle } from "./components/Subtitle";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { AVATAR_CONFIG } from "./registry/avatarConfig";
import { CAMERA_CUES } from "./registry/cameraCues";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1800;
  // +400ms 步间呼吸垫（2026-07-22）：真实配音的 mp3 自带尾部气口，估时没有
  // ——无音频预览里连续短句步会一步紧接一步，观感"突然加速"。
  return Math.max(1800, text.length * 250 + 400);
}

// 章节结构真相源（2026-07-22）：registry 源码写法六种形状实证不可靠解析——
// 工作台的确定性工具（镜头编排器/修复靶向）一律读这个运行时全局，
// 与页面实际渲染的结构永远一致，源码怎么写都无所谓。
if (typeof window !== "undefined") {
  (window as unknown as { __VF_STRUCTURE?: unknown }).__VF_STRUCTURE = CHAPTERS.map((c) => ({
    id: c.id,
    title: c.title,
    steps: c.narrations.length,
  }));
}

export default function App() {
  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  // Auto 模式未启动时抑制 stepper 的 Space 监听：否则启动播放的同一次按键
  // 会被当成"前进一步"，第 0 步的画面和配音会被跳过。
  const stepper = useStepper(CHAPTERS, {
    suppressSpace: mode === "auto" && !autoStarted,
  });
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  const { getAudioEl } = useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  // avatar-mount:v1 —— 确定性接线契约：字幕与数字人由 registry 数据驱动。
  // VideoForge 的 avatar_wire 阶段只重写 registry/avatarConfig.ts，不改本文件。
  const avatarAudioSources = useMemo(
    () =>
      AVATAR_CONFIG.enabled
        ? CHAPTERS.flatMap((chapter) =>
            chapter.narrations.map(
              (_, index) =>
                `${import.meta.env.BASE_URL}audio/${chapter.id}/${index + 1}.mp3`,
            ),
          )
        : [],
    [],
  );

  useEffect(() => {
    if (!AVATAR_CONFIG.enabled) return;
    const rootStyle = document.documentElement.style;
    rootStyle.setProperty("--stage-pad-x-end", `${AVATAR_CONFIG.reservePx}px`);
    rootStyle.setProperty("--avatar-window-w", `${AVATAR_CONFIG.windowWidthPx}px`);
    rootStyle.setProperty("--avatar-window-h", `${AVATAR_CONFIG.windowHeightPx}px`);
    rootStyle.setProperty(
      "--avatar-window-aspect",
      String(AVATAR_CONFIG.windowWidthPx / Math.max(1, AVATAR_CONFIG.windowHeightPx)),
    );
  }, []);

  // 数字人时刻（效果 v1）：host = 讲述者时刻，host-full = 开场全屏。
  // 与内容镜头同一份 registry 声明；未启用数字人时忽略。
  const hostCue = CAMERA_CUES[ch.id]?.[stepper.cursor.step]?.effect;
  const hostMode: "none" | "host" | "full" | "split" = !AVATAR_CONFIG.enabled
    ? "none"
    : hostCue === "host-full"
      ? "full"
      : hostCue === "host-split"
        ? "split"
        : hostCue === "host"
          ? "host"
          : "none";

  return (
    <>
      <Stage onAdvance={stepper.next}>
        {/* 效果 v1：镜头层只包章节画面——字幕与数字人在层外，镜头运动不影响它们 */}
        <div key={ch.id} className="scene">
          <EffectsProvider
            value={{ chapterId: ch.id, step: stepper.cursor.step, getAudioEl }}
          >
            <CameraLayer chapterId={ch.id} step={stepper.cursor.step}>
              <Cmp step={stepper.cursor.step} />
            </CameraLayer>
          </EffectsProvider>
        </div>
        {/* 边缘安全渐变（2026-07-22 用户提议）：镜头推拉时内容会滑过字幕区/
            数字人区，边缘本来就是非重点——底部与数字人侧各铺一条到底色的
            渐变，推过来的内容淡出而不是硬压。在镜头层之上、字幕/数字人之下。 */}
        <div className="edge-fade edge-fade--bottom" aria-hidden="true" />
        {AVATAR_CONFIG.enabled && <div className="edge-fade edge-fade--end" aria-hidden="true" />}
        {/* 钩子分屏期隐藏底部字幕：右栏大字本身就是字幕 */}
        {hostMode !== "split" && <Subtitle
          chapterId={ch.id}
          step={stepper.cursor.step}
          fallbackText={stepText}
          getAudioEl={getAudioEl}
        />}
        {/* 数字人时刻的内容压暗层：在画面之上、数字人之下 */}
        {AVATAR_CONFIG.enabled && (
          <div className={`host-dim${hostMode === "host" || hostMode === "full" ? " host-dim--on" : ""}`} aria-hidden="true" />
        )}
        {AVATAR_CONFIG.enabled && (
          <AvatarPresenter
            getAudioEl={getAudioEl}
            globalStep={stepper.globalIndex}
            audioSources={avatarAudioSources}
            hostMode={hostMode}
          />
        )}
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
