// AUTO-GENERATED by VideoForge avatar_wire — 手动项目可自行编辑。
// enabled=false 时 AvatarPresenter 完全不渲染、不预留版面。

export type AvatarPosition = "right-third" | "right-top" | "right-bottom";

export interface AvatarConfig {
  enabled: boolean;
  position: AvatarPosition;
  /** 正文为讲师区预留的右侧宽度（1920 stage 坐标系 px）。 */
  reservePx: number;
  windowWidthPx: number;
  windowHeightPx: number;
}

export const AVATAR_CONFIG: AvatarConfig = {
  enabled: false,
  position: "right-third",
  reservePx: 0,
  windowWidthPx: 252,
  windowHeightPx: 448,
};
