// AUTO-GENERATED by scripts/gen-subtitle-cues.mjs — do not hand-edit.
// Scaffold 占位：cues 生成前为空，Subtitle 组件自动回退整段旁白文本。

export interface SubtitleCue {
  text: string;
  startMs: number;
}

// chapterId -> per-step array of cues (index = step, 0-based)
export const SUBTITLE_CUES: Record<string, SubtitleCue[][]> = {};
